name: "Build"

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:
  build:
    name: "Build"
    runs-on: macos-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: "Checkout HEAD^2 for pull request"
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        git checkout HEAD^2

    - name: "Run build"
      env:
        VK_APP_ID: ${{ secrets.VK_APP_ID }}
        VK_SERVICE_TOKEN: ${{ secrets.VK_SERVICE_TOKEN }}
        VK_SECRET: ${{ secrets.VK_SECRET }}
      run: |
        xcodebuild test -project VK-ios-sdk.xcodeproj -scheme VKSdk -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 12" \
                        GCC_PREPROCESSOR_DEFINITIONS="VK_APP_ID=$VK_APP_ID VK_SERVICE_TOKEN=$VK_SERVICE_TOKEN VK_SECRET=$VK_SECRET"
